### ISSUE TITLE
begginner guide broken due to mkl requirement

### ISSUE THREAD

**Issue by franchesoni** [microsoft/Semi-supervised-learning#131]
## Bug

I just "Run all" the begginer example notebook and it fails in the second cell after an error in the first.
The root cause is the following
`ERROR: Could not find a version that satisfies the requirement mkl-fft==1.3.0 (from semilearn) (from versions: none)
ERROR: No matching distribution found for mkl-fft==1.3.0`
### Reproduce the Bug

go to `https://colab.research.google.com/drive/1lFygK31jWyTH88ktao6Ow-5nny5-B7v5#scrollTo=ChgugcBLJCkD` and `Run all`

### Error Messages and Logs

![image](https://github.com/microsoft/Semi-supervised-learning/assets/24411007/4806d61c-acae-42d1-9f28-6935a91f5858)

**Comment by Hhhhhhao** [comment]
Please refer to https://github.com/microsoft/Semi-supervised-learning/issues/120 for this similar problem.

**Comment by Hhhhhhao** [comment]
Fixed in PR #135

**Comment by ZahraaHM** [comment]
I have the same problem , just now I run the beginner example and it shows same error , it is not resolved, would you please solve the problem
